[package]
name = "spooky"
version = "1.0.0"
authors = ["n01e0 <noleo@vanillabeans.mobi>"]
edition = "2018"
description = "GMOコインのAPIをインタラクティブに叩くやつ"
readme = "README.md"

[dependencies]
gmo_coin = "*"
shrust = "*"
